flowchart TD
    A[Fetch Paper URLs] --> B[Database]
    B <--> D[Clean Papers]
    B <--> E[Profile Papers]
    B <--> F[Score Papers]
    B <--> G[Extract CoT]
    B <--> H[Validate CoT]
    B --> I[Filter CoT]
    E --> J[Profile Artifact]
    G --> K[CoT Artifacts]
    G --> L[Training File]
    H --> M[Validation Artifact]
    I --> N[Training File]
