---
- name: Profile paper
  block:
    - name: "Download PDF {{ current_url }} to {{ tmp_pdf_path }}"
      ansible.builtin.get_url:
        url: "{{ current_url }}"
        dest: "{{ tmp_pdf_path }}"
        mode: '0644'
        force: yes
      register: download_result
      until: download_result is succeeded
      retries: 3
      delay: 5

    - name: "Extract text from PDF: {{ current_url }}"
      text_extractor:
        path: "{{ tmp_pdf_path }}"
      register: extracted_text

    - name: "Run LWE Template: {{ template }} with preset: {{ profiler_preset }}"
      lwe_llm:
        preset: "{{ profiler_preset }}"
        template: "{{ template }}"
        template_vars:
          paper: "{{ extracted_text.content }}"
      register: lwe_results
      until: lwe_results is succeeded
      retries: 3
      delay: 5

    - name: "Run profiler script: {{ profiler_script }}"
      ansible.builtin.command:
        cmd: >-
          {{ profiler_script }}
          {{ profiler_preset | quote }}
          {{ database | quote }}
          {{ paper_id | quote }}
          {{ current_url | quote }}
          {{ lwe_results.response | quote }}
          {{ inference_results_directory | quote }}
      register: script_output

    - name: "Output script execution results: {{ profiler_script }}"
      ansible.builtin.debug:
        msg: "{{ script_output.stdout }}"

  rescue:
    - name: "Set processing status to 'failed' if any step fails"
      lwe_sqlite_query:
        db: "{{ database }}"
        query: "UPDATE papers SET processing_status = 'failed_profiling' WHERE id = ?"
        query_params:
          - "{{ paper_id }}"
